version: "3"
volumes:
  database:
    driver: local
services:
  postgres:
    image: postgres:latest
    container_name: turborepo_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - database:/var/lib/postgresql/data
